[project]
name = "my_project"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
r = ">=4.4"
r-tidyverse = "*"
r-sf = "*"
r-terra = "*"
r-stars = "*"
r-tmap = "*"
r-mlr3 = "*"
r-remotes = "*"
r-knitr = "*"
r-rmarkdown = "*"
r-tidygraph = "*"
r-leaflet = "*"
r-plotly = "*"
r-curl = "*"
r-languageserver = "*"